#!groovy

// Generated by IBM TransformationAdvisor
// Mon Oct 08 17:47:35 UTC 2018

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = '--version'
    test='false'
}